name: "Lighthouse-check"
description: "Run Lighthouse"
inputs:
  urls:
    description: "The urls to test"
    required: true
    default: ""
  performanceThreshold:
    description: "A treshold value for the performance category"
    required: false
  accessibilityThreshold:
     description: "A treshold value for the accessibility category"
     required: false
  bestPracticesThreshold: 
    description: "A treshold value for the best pratices category"
    required: false
  SEOThreshold: 
     description: "A treshold value for the SEO category"
     required: false
  PWAThreshold:  
    description: "A treshold value for the PWA category"
    required: false
runs:
  using: "node12"
  main: 'dist/index.js'
